# Generated by Django 3.2.18 on 2024-05-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='restauration',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
