# Generated by Django 5.0.4 on 2024-05-09 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_salle_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='photos',
            field=models.ImageField(default=datetime.datetime(2024, 5, 9, 15, 10, 58, 749663, tzinfo=datetime.timezone.utc), upload_to='static/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restauration',
            name='photos',
            field=models.ImageField(default=datetime.datetime(2024, 5, 9, 15, 11, 6, 899032, tzinfo=datetime.timezone.utc), upload_to='static/'),
            preserve_default=False,
        ),
    ]
