# Generated by Django 5.0.4 on 2024-05-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_equipement_photos_restauration_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='lieu',
            field=models.CharField(default='Dakar', max_length=100),
        ),
        migrations.AddField(
            model_name='salle',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
