# Generated by Django 5.0.4 on 2024-05-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_salle_lieu_salle_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='duree',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_debut',
            field=models.CharField(default='10:00', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_fin',
            field=models.CharField(default='12:00', max_length=100),
        ),
    ]
