# Generated by Django 3.2.18 on 2024-05-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
